let allStatesInfo = [
    {"Abbreviation":"CA","State":"California","Population":"39,536,653","Sq.Miles":"163,695","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"TX","State":"Texas","Population":"28,304,596","Sq.Miles":"268,596","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"FL","State":"Florida","Population":"20,984,400","Sq.Miles":"65,758","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"NY","State":"New York","Population":"19,849,399","Sq.Miles":"54,555","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"PA","State":"Pennsylvania","Population":"12,805,537","Sq.Miles":"46,054","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"IL","State":"Illinois","Population":"12,802,023","Sq.Miles":"57,914","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"OH","State":"Ohio","Population":"11,658,609","Sq.Miles":"44,826","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"GA","State":"Georgia","Population":"10,429,379","Sq.Miles":"59,425","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"NC","State":"North Carolina","Population":"10,273,419","Sq.Miles":"53,819","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"MI","State":"Michigan","Population":"9,962,311","Sq.Miles":"96,714","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"NJ","State":"New Jersey","Population":"9,005,644","Sq.Miles":"8,723","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"VA","State":"Virginia","Population":"8,470,020","Sq.Miles":"42,775","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"WA","State":"Washington","Population":"7,405,743","Sq.Miles":"71,298","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"AZ","State":"Arizona","Population":"7,016,270","Sq.Miles":"113,990","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"MA","State":"Massachusetts","Population":"6,859,819","Sq.Miles":"10,554","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"TN","State":"Tennessee","Population":"6,715,984","Sq.Miles":"42,144","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"IN","State":"Indiana","Population":"6,666,818","Sq.Miles":"36,420","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"MO","State":"Missouri","Population":"6,113,532","Sq.Miles":"69,707","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"MD","State":"Maryland","Population":"6,052,177","Sq.Miles":"12,406","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"WI","State":"Wisconsin","Population":"5,795,483","Sq.Miles":"65,496","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"CO","State":"Colorado","Population":"5,607,154","Sq.Miles":"104,094","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"MN","State":"Minnesota","Population":"5,576,606","Sq.Miles":"86,936","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"SC","State":"South Carolina","Population":"5,024,369","Sq.Miles":"32,020","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"AL","State":"Alabama","Population":"4,874,747","Sq.Miles":"52,420","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"LA","State":"Louisiana","Population":"4,684,333","Sq.Miles":"52,378","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"KY","State":"Kentucky","Population":"4,454,189","Sq.Miles":"40,408","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"OR","State":"Oregon","Population":"4,142,776","Sq.Miles":"98,379","TotEnergy":"","RenewEnergy":"","CustAccts":""},
     {"Abbreviation":"OK","State":"Oklahoma","Population":"3,930,864","Sq.Miles":"69,899","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"CT","State":"Connecticut","Population":"3,588,184","Sq.Miles":"5,543","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"IA","State":"Iowa","Population":"3,145,711","Sq.Miles":"56,273","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"UT","State":"Utah","Population":"3,101,833","Sq.Miles":"84,897","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"AR","State":"Arkansas","Population":"3,004,279","Sq.Miles":"53,179","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"NV","State":"Nevada","Population":"2,998,039","Sq.Miles":"110,572","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"MS","State":"Mississippi","Population":"2,984,100","Sq.Miles":"48,432","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"KS","State":"Kansas","Population":"2,913,123","Sq.Miles":"82,278","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"NM","State":"New Mexico","Population":"2,088,070","Sq.Miles":"121,590","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"NE","State":"Nebraska","Population":"1,920,076","Sq.Miles":"77,348","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"WV","State":"West Virginia","Population":"1,815,857","Sq.Miles":"24,230","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"ID","State":"Idaho","Population":"1,716,943","Sq.Miles":"83,569","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"HI","State":"Hawaii","Population":"1,427,538","Sq.Miles":"10,932","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"NH","State":"New Hampshire","Population":"1,342,795","Sq.Miles":"9,349","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"ME","State":"Maine","Population":"1,335,907","Sq.Miles":"35,380","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"RI","State":"Rhode Island","Population":"1,059,639","Sq.Miles":"1,545","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"MT","State":"Montana","Population":"1,050,493","Sq.Miles":"147,040","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"DE","State":"Delaware","Population":"961,939","Sq.Miles":"2,489","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"SD","State":"South Dakota","Population":"869,666","Sq.Miles":"77,116","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"ND","State":"North Dakota","Population":"755,393","Sq.Miles":"70,698","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"AK","State":"Alaska","Population":"739,795","Sq.Miles":"665,384","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"VT","State":"Vermont","Population":"623,657","Sq.Miles":"9,616","TotEnergy":"","RenewEnergy":"","CustAccts":""},
    {"Abbreviation":"WY","State":"Wyoming","Population":"579,315","Sq.Miles":"97,813","TotEnergy":"","RenewEnergy":"","CustAccts":""},
]